import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from 'next/link';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Link href="/courses">
          <button>Courses</button>
        </Link>
        <Link href="/assignments">
          <button>Upcoming Assignments</button>
        </Link>
        <Link href="/notifications">
          <button>Notifications</button>
        </Link>
        <Link href="/profile-settings">
          <button>Profile Settings</button>
        </Link>
        <hr/>
        {children} 
      </body>
    </html>
  );
}
