/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileSettingsRouteImport } from './routes/profile-settings'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ManageCoursesRouteImport } from './routes/manage-courses'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as CoursesCourseIdIndexRouteImport } from './routes/courses.$courseId.index'
import { Route as CoursesCourseIdCourseInfoRouteImport } from './routes/courses.$courseId.course-info'
import { Route as CoursesCourseIdAssignmentsRouteImport } from './routes/courses.$courseId.assignments'

const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/profile-settings',
  path: '/profile-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageCoursesRoute = ManageCoursesRouteImport.update({
  id: '/manage-courses',
  path: '/manage-courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesCourseIdIndexRoute = CoursesCourseIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesCourseIdRoute,
} as any)
const CoursesCourseIdCourseInfoRoute =
  CoursesCourseIdCourseInfoRouteImport.update({
    id: '/course-info',
    path: '/course-info',
    getParentRoute: () => CoursesCourseIdRoute,
  } as any)
const CoursesCourseIdAssignmentsRoute =
  CoursesCourseIdAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => CoursesCourseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/courses': typeof CoursesRouteWithChildren
  '/manage-courses': typeof ManageCoursesRoute
  '/notifications': typeof NotificationsRoute
  '/profile-settings': typeof ProfileSettingsRoute
  '/courses/$courseId': typeof CoursesCourseIdRouteWithChildren
  '/courses/': typeof CoursesIndexRoute
  '/courses/$courseId/assignments': typeof CoursesCourseIdAssignmentsRoute
  '/courses/$courseId/course-info': typeof CoursesCourseIdCourseInfoRoute
  '/courses/$courseId/': typeof CoursesCourseIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/manage-courses': typeof ManageCoursesRoute
  '/notifications': typeof NotificationsRoute
  '/profile-settings': typeof ProfileSettingsRoute
  '/courses': typeof CoursesIndexRoute
  '/courses/$courseId/assignments': typeof CoursesCourseIdAssignmentsRoute
  '/courses/$courseId/course-info': typeof CoursesCourseIdCourseInfoRoute
  '/courses/$courseId': typeof CoursesCourseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/courses': typeof CoursesRouteWithChildren
  '/manage-courses': typeof ManageCoursesRoute
  '/notifications': typeof NotificationsRoute
  '/profile-settings': typeof ProfileSettingsRoute
  '/courses/$courseId': typeof CoursesCourseIdRouteWithChildren
  '/courses/': typeof CoursesIndexRoute
  '/courses/$courseId/assignments': typeof CoursesCourseIdAssignmentsRoute
  '/courses/$courseId/course-info': typeof CoursesCourseIdCourseInfoRoute
  '/courses/$courseId/': typeof CoursesCourseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assignments'
    | '/courses'
    | '/manage-courses'
    | '/notifications'
    | '/profile-settings'
    | '/courses/$courseId'
    | '/courses/'
    | '/courses/$courseId/assignments'
    | '/courses/$courseId/course-info'
    | '/courses/$courseId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assignments'
    | '/manage-courses'
    | '/notifications'
    | '/profile-settings'
    | '/courses'
    | '/courses/$courseId/assignments'
    | '/courses/$courseId/course-info'
    | '/courses/$courseId'
  id:
    | '__root__'
    | '/'
    | '/assignments'
    | '/courses'
    | '/manage-courses'
    | '/notifications'
    | '/profile-settings'
    | '/courses/$courseId'
    | '/courses/'
    | '/courses/$courseId/assignments'
    | '/courses/$courseId/course-info'
    | '/courses/$courseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssignmentsRoute: typeof AssignmentsRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  ManageCoursesRoute: typeof ManageCoursesRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile-settings': {
      id: '/profile-settings'
      path: '/profile-settings'
      fullPath: '/profile-settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-courses': {
      id: '/manage-courses'
      path: '/manage-courses'
      fullPath: '/manage-courses'
      preLoaderRoute: typeof ManageCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/$courseId/': {
      id: '/courses/$courseId/'
      path: '/'
      fullPath: '/courses/$courseId/'
      preLoaderRoute: typeof CoursesCourseIdIndexRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
    '/courses/$courseId/course-info': {
      id: '/courses/$courseId/course-info'
      path: '/course-info'
      fullPath: '/courses/$courseId/course-info'
      preLoaderRoute: typeof CoursesCourseIdCourseInfoRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
    '/courses/$courseId/assignments': {
      id: '/courses/$courseId/assignments'
      path: '/assignments'
      fullPath: '/courses/$courseId/assignments'
      preLoaderRoute: typeof CoursesCourseIdAssignmentsRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
  }
}

interface CoursesCourseIdRouteChildren {
  CoursesCourseIdAssignmentsRoute: typeof CoursesCourseIdAssignmentsRoute
  CoursesCourseIdCourseInfoRoute: typeof CoursesCourseIdCourseInfoRoute
  CoursesCourseIdIndexRoute: typeof CoursesCourseIdIndexRoute
}

const CoursesCourseIdRouteChildren: CoursesCourseIdRouteChildren = {
  CoursesCourseIdAssignmentsRoute: CoursesCourseIdAssignmentsRoute,
  CoursesCourseIdCourseInfoRoute: CoursesCourseIdCourseInfoRoute,
  CoursesCourseIdIndexRoute: CoursesCourseIdIndexRoute,
}

const CoursesCourseIdRouteWithChildren = CoursesCourseIdRoute._addFileChildren(
  CoursesCourseIdRouteChildren,
)

interface CoursesRouteChildren {
  CoursesCourseIdRoute: typeof CoursesCourseIdRouteWithChildren
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCourseIdRoute: CoursesCourseIdRouteWithChildren,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssignmentsRoute: AssignmentsRoute,
  CoursesRoute: CoursesRouteWithChildren,
  ManageCoursesRoute: ManageCoursesRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
